//
//  SearchRangeWorker.swift
//  AlboAeroTestSZ
//
//  Created by Sergio Eduardo Zorrilla Arellano on 07/06/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
import CoreLocation

protocol SearchRangeWorkerInterface {
    func askLocationPermission(completion: @escaping (_ result: SearchRangeModels.FetchSearchRangeAksLocation.Response) -> Void)
}

class SearchRangeWorker: SearchRangeWorkerInterface {
    func askLocationPermission(completion: @escaping (SearchRangeModels.FetchSearchRangeAksLocation.Response) -> Void) {
        var response = SearchRangeModels.FetchSearchRangeAksLocation.Response()
        var locationManager = CLLocationManager()
        locationManager = CLLocationManager()
        locationManager.requestWhenInUseAuthorization()
        locationManager.distanceFilter = kCLDistanceFilterNone
        locationManager.desiredAccuracy = kCLLocationAccuracyBest

        response.locationManager = locationManager
        completion(response)
    }
}
