//
//  SearchRangeInteractor.swift
//  AlboAeroTestSZ
//
//  Created by Sergio Eduardo Zorrilla Arellano on 07/06/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol SearchRangeInteractorInterface {
    func fetchSearchRangeLocation(request: SearchRangeModels.FetchSearchRangeAksLocation.Request)
}

protocol SearchRangeDataStore {
    
}

class SearchRangeInteractor: SearchRangeInteractorInterface, SearchRangeDataStore {

    // MARK: - Properties
    
    var presenter: SearchRangePresenterInterface?
    var worker: SearchRangeWorkerInterface = SearchRangeWorker()
    
    // MARK: - SearchRangeInteractorInterface

    func fetchSearchRangeLocation(request: SearchRangeModels.FetchSearchRangeAksLocation.Request) {
        self.worker.askLocationPermission { response in
            self.presenter?.presentSearchRangeLocation(response: response)
        }
    }
}
