//
//  SearchRangePresenter.swift
//  AlboAeroTestSZ
//
//  Created by Sergio Eduardo Zorrilla Arellano on 07/06/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchRangePresenterInterface {
    func presentSearchRangeLocation(response: SearchRangeModels.FetchSearchRangeAksLocation.Response)
}

class SearchRangePresenter: SearchRangePresenterInterface {

    // MARK: - Properties
    
    weak var viewController: SearchRangeDisplayInterface?
    
    // MARK: - SearchRangePresenterInterface

    func presentSearchRangeLocation(response: SearchRangeModels.FetchSearchRangeAksLocation.Response) {
        viewController?.askLocationPermission(permission: response)
    }
}
