//
//  ListAirportsRouter.swift
//  AlboAeroTestSZ
//
//  Created by Sergio Eduardo Zorrilla Arellano on 07/06/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListAirportsRouterInterface {
    
}

protocol ListAirportsDataPassing {
    var dataStore: ListAirportsDataStore? { get }
}

class ListAirportsRouter: ListAirportsRouterInterface, ListAirportsDataPassing {
    
    // MARK: - Properties
    
    weak var viewController: ListAirportsViewController?
    var dataStore: ListAirportsDataStore?
}
