//
//  ListAirportsPresenter.swift
//  AlboAeroTestSZ
//
//  Created by Sergio Eduardo Zorrilla Arellano on 07/06/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListAirportsPresenterInterface {
    func presentListAirports(response: ListAirportsModels.FetchListAirports.Response)
    func presentListAirportsFromApi(response: ListAirportsModels.FetchAirportsList.Response)
}

class ListAirportsPresenter: ListAirportsPresenterInterface {
    
    // MARK: - Properties
    
    weak var viewController: ListAirportsDisplayInterface?
    
    // MARK: - ListAirportsPresenterInterface
    
    func presentListAirports(response: ListAirportsModels.FetchListAirports.Response) {
        let viewModel = ListAirportsModels.FetchListAirports.ViewModel(coordinates: response.coordinates,
                                                                       radiusKm: response.radiusKm)
        viewController?.displayListAirports(viewModel: viewModel)
    }

    func presentListAirportsFromApi(response: ListAirportsModels.FetchAirportsList.Response) {
        let viewModel = ListAirportsModels.FetchAirportsList.ViewModel(airports: response.airports)
        viewController?.displayListAirportsApi(viewModel: viewModel)
    }

}
