//
//  ListAirportsInteractor.swift
//  AlboAeroTestSZ
//
//  Created by Sergio Eduardo Zorrilla Arellano on 07/06/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
import CoreLocation

protocol ListAirportsInteractorInterface {
    func fetchListAirports(request: ListAirportsModels.FetchListAirports.Request)
    func getListAirports(request: MapAirportsModels.FetchAirportsMap.Request)
}

protocol ListAirportsDataStore {
    var coordinates: CLLocationCoordinate2D {get set}
    var radiusKm: Int {get set}
}

class ListAirportsInteractor: ListAirportsInteractorInterface, ListAirportsDataStore {
   
    // MARK: - Properties
    
    var presenter: ListAirportsPresenterInterface?
    var worker: ListAirportsWorkerInterface = ListAirportsWorker()
    var coordinates = CLLocationCoordinate2D()
    var radiusKm = 0
    // MARK: - ListAirportsInteractorInterface

    func fetchListAirports(request: ListAirportsModels.FetchListAirports.Request) {
        let response = ListAirportsModels.FetchListAirports.Response(coordinates: self.coordinates,
                                                                   radiusKm: radiusKm)
        presenter?.presentListAirports(response: response)
    }

    func getListAirports(request: MapAirportsModels.FetchAirportsMap.Request) {
        self.worker.getAirports(params: request) { response in
            self.presenter?.presentListAirportsFromApi(response: response)
        }
    }
}
