//
//  MapAirportsRouter.swift
//  AlboAeroTestSZ
//
//  Created by Sergio Eduardo Zorrilla Arellano on 07/06/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MapAirportsRouterInterface {
    
}

protocol MapAirportsDataPassing {
    var dataStore: MapAirportsDataStore? { get }
}

class MapAirportsRouter: MapAirportsRouterInterface, MapAirportsDataPassing {
    
    // MARK: - Properties
    
    weak var viewController: MapAirportsViewController?
    var dataStore: MapAirportsDataStore?
}
