//
//  MapAirportsPresenter.swift
//  AlboAeroTestSZ
//
//  Created by Sergio Eduardo Zorrilla Arellano on 07/06/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MapAirportsPresenterInterface {
    func presentMapAirports(response: MapAirportsModels.FetchMapAirports.Response)
    func presentMapAirportsFromApi(response: MapAirportsModels.FetchAirportsMap.Response)
}

class MapAirportsPresenter: MapAirportsPresenterInterface {
    // MARK: - Properties
    
    weak var viewController: MapAirportsDisplayInterface?
    
    // MARK: - MapAirportsPresenterInterface
    
    func presentMapAirports(response: MapAirportsModels.FetchMapAirports.Response) {
        let viewModel = MapAirportsModels.FetchMapAirports.ViewModel(coordinates: response.coordinates,
                                                                     radiusKm: response.radiusKm)
        viewController?.displayMapAirports(viewModel: viewModel)
    }

    func presentMapAirportsFromApi(response: MapAirportsModels.FetchAirportsMap.Response) {
        let viewModel = MapAirportsModels.FetchAirportsMap.ViewModel(airports: response.airports)
        viewController?.displayMapAirportsApi(viewModel: viewModel)
        
    }
    
}
