//
//  MapAirportsInteractor.swift
//  AlboAeroTestSZ
//
//  Created by Sergio Eduardo Zorrilla Arellano on 07/06/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
import CoreLocation

protocol MapAirportsInteractorInterface {
    func fetchMapAirports(request: MapAirportsModels.FetchMapAirports.Request)
    func getMapAirports(request: MapAirportsModels.FetchAirportsMap.Request)
}

protocol MapAirportsDataStore {
    var coordinates: CLLocationCoordinate2D {get set}
    var radiusKm: Int {get set}
}

class MapAirportsInteractor: MapAirportsInteractorInterface, MapAirportsDataStore {
    // MARK: - Properties
    
    var presenter: MapAirportsPresenterInterface?
    var worker: MapAirportsWorkerInterface = MapAirportsWorker()
    var coordinates = CLLocationCoordinate2D()
    var radiusKm = 0
    // MARK: - MapAirportsInteractorInterface
    
    func fetchMapAirports(request: MapAirportsModels.FetchMapAirports.Request) {
        let response = MapAirportsModels.FetchMapAirports.Response(coordinates: self.coordinates,
                                                                   radiusKm: radiusKm)
        presenter?.presentMapAirports(response: response)
    }

    func getMapAirports(request: MapAirportsModels.FetchAirportsMap.Request) {
        self.worker.getAirports(params: request) { response in
            self.presenter?.presentMapAirportsFromApi(response: response)
        }
    }
}
